blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

cheatsheets/urls.py
from django.urls import path
from . import views


app_name = 'cheatsheets'

urlpatterns = [
    path('', views.all_cheatsheets, name='all_cheatsheets'),
    path('<int:cheatsheet_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('cheatsheets/', include('cheatsheets.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()


    def __str__(self):
        return  self.title

cheatsheets/models.py
from django.db import models


class Cheatsheet(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='cheatsheets/images/')
    commands = models.JSONField()
    pdf = models.FileField(blank=True, upload_to='cheatsheets/pdfs/')

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


    def __str__(self):
        return  self.title

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.all().order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

cheatsheets/views.py
from django.shortcuts import render, get_object_or_404

from .models import Cheatsheet


def all_cheatsheets(request):
    cheatsheets = Cheatsheet.objects.all()
    return render(request, 'cheatsheets/all_cheatsheets.html', {'cheatsheets': cheatsheets})


def detail(request, cheatsheet_id):
    cheatsheet = get_object_or_404(Cheatsheet, pk=cheatsheet_id)
    return render(request, 'cheatsheets/detail.html', {'cheatsheet': cheatsheet})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):

    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Bård has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

cheatsheets/templates/cheatsheets/all_cheatsheets.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}



<h2 class="mt-5">Cheatsheets</h2>
<hr>
<div class="row">
  {% for cheatsheet in cheatsheets %}
  <div class="col-lg-4 col-md-6">

<a href="{% url 'cheatsheets:detail' cheatsheet.id  %}">
    <h3>{{ cheatsheet.title }}</h3>

      <img src="{{ cheatsheet.image.url }}" class="img-fluid mb-2">
    </a>


  </div>
  {% endfor %}
</div>



{% endblock %}

cheatsheets/templates/cheatsheets/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="cheatsheetdetailtitle">{{ cheatsheet.title }}</h1>



<div class="row justify-content-center my-3">
  <div class="col-12">
    <img src="{{ cheatsheet.image.url }}" class="img-fluid">
  </div>
</div>


<div class="row justify-content-center my-3">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">Command</th>
      <th scope="col">Description</th>
      <th scope="col">PDF</th>
      <th scope="col">Link</th>
        <th align="center" scope="col">Copy</th>
    </tr>
  </thead>
  <tbody>

    {% for command in cheatsheet.commands %}


    <tr>
      <td>{{command.command}}</td>
      <td>{{command.description}}</td>
      <td><a href="{{ command.pdf.url }}">pdf</a></td>
      <td>
          {% if command.URL %}
          <a href="{{ command.URL }}">web</a>
      {% endif %}
      </td>
    <td><button type="button" class="btn btn-default btn-copy js-tooltip js-copy" data-toggle="tooltip" data-placement="bottom" data-copy="{{ command.command }}" title="Copy to clipboard"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-clipboard" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
  <path fill-rule="evenodd" d="M9.5 1h-3a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
</svg>
    </button>
    </td>
    </tr>

{% endfor %}


  </tbody>
</table>

</div>



{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>Bård-Inge Pettersen</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Bård's Logo">
        <span id="my-name">Bård-Inge Pettersen</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav-link" href="{% url "cheatsheets:all_cheatsheets" %}">Cheatsheets</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/cv.pdf" %}">CV</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/bardinge.pettersen" target="_blank">Facebook</a>
          </li>
         {% comment %} <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>{% endcomment %}
        </ul>
      </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="{% static 'cheatsheets/app.js'  %}"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/profile.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h3 id="hometext" class="font-weight-bold">I am a lecturer at <a href="http://www.himolde.no" target="_blank">Høgskolen i Molde!</a></h3>
  </div>
</div>

<h2 class="mt-5">Interests</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}